fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

govwiki_api:
    resource: "@GovWikiApiBundle/Resources/config/routing.yml"
    prefix:   /api

govwiki_user:
    resource: "@GovWikiUserBundle/Resources/config/routing.yml"
    prefix:   /

govwiki_admin:
    resource: "@GovWikiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

govwiki_frontend:
    resource: "@GovWikiFrontendBundle/Resources/config/routing.yml"
    prefix: /