main:
    resource: "@GovWikiAdminBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /

government:
    resource: "@GovWikiAdminBundle/Controller/GovernmentController.php"
    type:     annotation

electedofficial:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialController.php"
    type:     annotation

legislation:
    resource: "@GovWikiAdminBundle/Controller/LegislationController.php"
    type:     annotation

electedofficialvote:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialVoteController.php"
    type:     annotation
    prefix:   /

contribution:
    resource: "@GovWikiAdminBundle/Controller/ContributionController.php"
    type:     annotation
    prefix:   /

endorsement:
    resource: "@GovWikiAdminBundle/Controller/EndorsementController.php"
    type:     annotation
    prefix:   /

publicstatement:
    resource: "@GovWikiAdminBundle/Controller/PublicStatementController.php"
    type:     annotation
    prefix:   /

createrequest:
    resource: "@GovWikiAdminBundle/Controller/CreateRequestController.php"
    type:     annotation

editrequest:
    resource: "@GovWikiAdminBundle/Controller/EditRequestController.php"
    type:     annotation

user:
    resource: "@GovWikiAdminBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user

map:
    resource: "@GovWikiAdminBundle/Controller/MapController.php"
    type:     annotation

format:
    resource: "@GovWikiAdminBundle/Controller/FormatController.php"
    type:     annotation

tab:
    resource: "@GovWikiAdminBundle/Controller/TabController.php"
    type:     annotation

category:
    resource: "@GovWikiAdminBundle/Controller/CategoryController.php"
    type:     annotation