main:
    resource: "@GovWikiAdminBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /

government:
    resource: "@GovWikiAdminBundle/Controller/GovernmentController.php"
    type:     annotation
    prefix:   /government

electedofficial:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialController.php"
    type:     annotation
    prefix:   /electedofficial

legislation:
    resource: "@GovWikiAdminBundle/Controller/LegislationController.php"
    type:     annotation
    prefix:   /legislation

electedofficialvote:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialVoteController.php"
    type:     annotation
    prefix:   /

contribution:
    resource: "@GovWikiAdminBundle/Controller/ContributionController.php"
    type:     annotation
    prefix:   /

endorsement:
    resource: "@GovWikiAdminBundle/Controller/EndorsementController.php"
    type:     annotation
    prefix:   /

publicstatement:
    resource: "@GovWikiAdminBundle/Controller/PublicStatementController.php"
    type:     annotation
    prefix:   /

createrequest:
    resource: "@GovWikiAdminBundle/Controller/CreateRequestController.php"
    type:     annotation
    prefix:   /createrequest

editrequest:
    resource: "@GovWikiAdminBundle/Controller/EditRequestController.php"
    type:     annotation
    prefix:   /editrequest

user:
    resource: "@GovWikiAdminBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user
