government:
    resource: "@GovWikiApiBundle/Controller/GovernmentController.php"
    type:     annotation
    prefix:   government

elected-official:
    resource: "@GovWikiApiBundle/Controller/ElectedOfficialController.php"
    type:     annotation
    prefix:   elected-official

createrequest:
    resource: "@GovWikiApiBundle/Controller/CreateRequestController.php"
    type:     annotation
    prefix:   createrequest

user:
    resource: "@GovWikiApiBundle/Controller/UserController.php"
    type:     annotation
    prefix:   user

url:
    resource: "@GovWikiApiBundle/Controller/UrlController.php"
    type:     annotation
    prefix:   url
